---
- hosts: all
  sudo: true
  tasks:
  - name: GetWebtatic
    get_url: url=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm dest=/root/ validate_certs=no
  - name: Webtatic repo
    yum: name=/root/webtatic-release.rpm state=present
  - name: Install various packages
    yum: name=zlib,libmemcached,libmemcached-devel,zlib-devel,memcached,bzip2-devel,openssl-devel,ncurses-devel,jwhois,cyrus-sasl-devel,libyaml-devel,vim,ntp,java,openssh,libssh2,openssh-clients,openssh-askpass,openssh-server state=present
  - name: RepoPercona
    yum_repository:
            name: percona
            description: Percona YUM
            baseurl: http://repo.percona.com/release/$releasever/RPMS/$basearch
            gpgcheck: no
  - name: Install Percona server
    yum: name=Percona-Server-server-57 state=present validate_certs=yes update_cache=yes
  - name: install php7 and httpd
    yum: name=php70w,php70w-opcache,php70w-mysql,php70w-pdo,php70w-devel,php70w-pear,httpd,php70w-ldap,php70w-mbstring state=present  
  - selinux:
     state: disabled
  - name: delete default mysql config file
    file: path=/etc/percona.conf.d/mysqld.cnf state=absent
  - name: Delete MySQL data directory
    file:
      path: /mnt/mysql
      state: absent
  - name: Delete MySQL data directory
    file:
      path: /mnt/mysql
      owner: mysql
      group: mysql
      mode: 0755
      state: directory
  - name: delete MySql cnf file
    file:
      path: /etc/my.cnf
      state: absent
  - name: create MySql cnf file
    file:
      path: /etc/my.cnf
      state: touch
      owner: root
      mode: 0755
  - name: update MySql cnf for six instances
    lineinfile: dest=/etc/my.cnf
            regexp='^'
            line='[mysqld@c] \n user    = mysql \n pid-file = =/var/run/mysqld/mysqld.pid \n socket   = /var/lib/mysql/mysqld.sock \n log-error = /var/log/mysqldc.log \n port    = 3306 \n datadir   = /mnt/mysql/c \n [mysqld@d1] \n user   = mysql \n pid-file = /var/run/mysqld/mysqld1.pid \n socket   = /var/lib/mysql/mysqld1.sock \n log-error  = /var/log/mysqldd1.log \n port   = 14001 \n datadir    = /mnt/mysql/d1 \n [mysqld@d2] \n user    = mysql \n pid-file = /var/run/mysqld/mysqld2.pid \n socket   = /var/lib/mysql/mysqld2.sock \n log-error  = /var/log/mysqldd2.log \n port   = 14002 \n datadir    = /mnt/mysql/d2 \n  \n [mysqld@d3] \n user    = mysql \n pid-file = /var/run/mysqld/mysqld3.pid \n socket   = /var/lib/mysql/mysqld3.sock \n log-error  = /var/log/mysqldd2.log \n port   = 14003 \n datadir    = /mnt/mysql/d3 \n  \n  \n [mysqld@d4] \n user    = mysql \n pid-file = /var/run/mysqld/mysqld4.pid \n socket   = /var/lib/mysql/mysqld4.sock \n log-error  = /var/log/mysqldd2.log \n port   = 14004 \n datadir    = /mnt/mysql/d4 \n  \n [mysqld@d5] \n user    = mysql \n pid-file = /var/run/mysqld/mysqld5.pid \n socket   = /var/lib/mysql/mysqld5.sock \n log-error  = /var/log/mysqldd2.log \n port   = 14005 \n datadir    = /mnt/mysql/d5 \n'
            state=present
  - name: initialize MySQL data directoris in non secure mode
    shell: mysqld --no-defaults --basedir=/mnt/mysql --user=mysql --datadir=c  --initialize-insecure --skip-ssl --explicit-defaults-for-timestamp --log-error-verbosity=1;
  - shell: mysqld --no-defaults --basedir=/mnt/mysql --user=mysql --datadir=d1 --initialize-insecure --skip-ssl --explicit-defaults-for-timestamp --log-error-verbosity=1;
  - shell: mysqld --no-defaults --basedir=/mnt/mysql --user=mysql --datadir=d2  --initialize-insecure --skip-ssl --explicit-defaults-for-timestamp --log-error-verbosity=1;
  - shell: mysqld --no-defaults --basedir=/mnt/mysql --user=mysql --datadir=d3  --initialize-insecure --skip-ssl --explicit-defaults-for-timestamp --log-error-verbosity=1;
  - shell: mysqld --no-defaults --basedir=/mnt/mysql --user=mysql --datadir=d4  --initialize-insecure --skip-ssl --explicit-defaults-for-timestamp --log-error-verbosity=1;
  - shell: mysqld --no-defaults --basedir=/mnt/mysql --user=mysql --datadir=d5  --initialize-insecure --skip-ssl --explicit-defaults-for-timestamp --log-error-verbosity=1;
  - name: Start mysql instances
    systemd:  name=mysqld@c  enabled=yes state=started
  - systemd:  name=mysqld@d1 enabled=yes state=started
  - systemd:  name=mysqld@d2 enabled=yes state=started
  - systemd:  name=mysqld@d3 enabled=yes state=started
  - systemd:  name=mysqld@d4 enabled=yes state=started
  - systemd:  name=mysqld@d5 enabled=yes state=started






#  - name: install composer/download first
#    get_url: url=https://getcomposer.org/installer dest=/tmp/installer validate_certs=no
#  - name: install composer
#    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
#  - name: rename composer.phar to composer
#    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
#  - name: make composer executable
#    file:
#     path: /usr/local/bin/composer
#     mode: a+x
#     state: file

  - service:
         name: httpd
         state: reloaded
#      - service: name=httpd state= reloaded
